name: sync query zone

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '29 13 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out PSL
      uses: actions/checkout@v4
      with:
        repository: publicsuffix/list
        path: list
        sparse-checkout: 'public_suffix_list.dat'
        sparse-checkout-cone-mode: false
    - id: check
      name: Check if zone is up to date
      env:
        TOKEN: ${{ secrets.DESEC_TOKEN }}
      run: 'echo $(curl -sS --fail-with-body https://desec.io/api/v1/domains/query.publicsuffix.zone/rrsets/@/TXT/ -H@<(cat <<< "Authorization: Token ${TOKEN}") | jq .records[0] | egrep -o "[0-9a-f]{64}") list/public_suffix_list.dat | sha256sum -c'
      continue-on-error: true

    - name: Set up Python
      if: steps.check.outcome == 'failure'
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      if: steps.check.outcome == 'failure'
      run: |
        python -m pip install --upgrade pip
        pip install psl-dns requests
    - name: Check out sync tools
      if: steps.check.outcome == 'failure'
      uses: actions/checkout@v4
      with:
        repository: desec-io/desec-tools
        path: desec-tools
    - name: Run sync
      if: steps.check.outcome == 'failure'
      env:
        TOKEN: ${{ secrets.DESEC_TOKEN }}
      working-directory: ./desec-tools
      run: psl-dns_parse ../list/public_suffix_list.dat | ./patch_zone.sh query.publicsuffix.zone -
    - name: Print PATCH request data
      if: steps.check.outcome == 'failure'
      working-directory: ./desec-tools
      run: cat *.json
